tags:
  proxy: false # enable if you want/need giphy/youtube/etc proxying
  spar: false # enable if you want/need Single-Sign-On (SSO)

cassandra-migrations:
#  images:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  cassandra:
    host: cassandra-ephemeral
    replicaCount: 1

elasticsearch-index:
  elasticsearch:
    host: elasticsearch-ephemeral
  cassandra:
    host: cassandra-ephemeral

brig:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  config:
    cassandra:
      host: cassandra-ephemeral
      replicaCount: 1
    elasticsearch:
      host: elasticsearch-ephemeral
    useSES: false
    aws:
      # change if using real AWS
      sqsEndpoint: http://fake-aws-sqs:4568
      dynamoDBEndpoint: http://fake-aws-dynamodb:4567
      # these must match the table names created on fake or real AWS services
      internalQueue: integration-brig-events-internal
      prekeyTable: integration-brig-prekeys
    externalUrls:
      nginz: https://api-dev.social.network # change this
      teamSettings: https://teams-dev.social.network # change this (on unset if team settings are not used)
      teamCreatorWelcome: https://teams-dev.social.network/login # change this
      teamMemberWelcome: https://society-dev.social.network/download # change this
    optSettings:
      setCookieDomain: social.network # change this
    emailSMS:
      general:
        emailSender: mail@social.network # change this
        smsSender: "insert-sms-sender-for-twilio" # change this if SMS support is desired
    smtp:
      host: demo-smtp # change this if you want to use your own SMTP server
      port: 25        # change this
      connType: plain # change this. Possible values: plain|ssl|tls
#    proxy:
#      httpProxy: "http://proxy-dev.social.network"
#      httpsProxy: "https://proxy-dev.social.network"
#      noProxyList:
#        - "local-dev.social.network"
#        - "10.23.0.0/16"

proxy:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
#  config:
#    proxy:
#      httpProxy: "http://proxy-dev.social.network"
#      httpsProxy: "https://proxy-dev.social.network"
#      noProxyList:
#        - "local-dev.social.network"
#        - "10.23.0.0/16"

cannon:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  # For demo mode only, we don't need to keep websocket connections open on chart upgrades
  drainTimeout: 10

cargohold:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  config:
    aws:
      # change if using real AWS
      s3Bucket: dummy-bucket
      s3Endpoint: http://fake-aws-s3:9000
      s3DownloadEndpoint: https://assets-dev.social.network
#    proxy:
#      httpProxy: "http://proxy-dev.social.network"
#      httpsProxy: "https://proxy-dev.social.network"
#      noProxyList:
#        - "local-dev.social.network"
#        - "10.23.0.0/16"

galley:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  config:
    cassandra:
      host: cassandra-ephemeral
      replicaCount: 1
    settings:
      # prefix URI used when inviting users to a conversation by link
      conversationCodeURI: https://social.network/join/ # change this
#    proxy:
#      httpProxy: "http://proxy-dev.social.network"
#      httpsProxy: "https://proxy-dev.social.network"
#      noProxyList:
#        - "local-dev.social.network"
#        - "10.23.0.0/16"

gundeck:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  config:
    cassandra:
      host: cassandra-ephemeral
      replicaCount: 1
    aws:
      # change if using real AWS
      account: "123456789012"
      region: eu-west-1
      arnEnv: integration
      queueName: integration-gundeck-events
      sqsEndpoint: http://fake-aws-sqs:4568
      snsEndpoint: http://fake-aws-sns:4575
#    proxy:
#      httpProxy: "http://proxy-dev.social.network"
#      httpsProxy: "https://proxy-dev.social.network"
#      noProxyList:
#        - "local-dev.social.network"
#        - "10.23.0.0/16"

nginz:
  replicaCount: 1
  config:
    ws:
      useProxyProtocol: false
#  images:
#    nginz:
#      tag: some-tag (only override if you want a newer/different version than what is in the chart)
  nginx_conf:
    # using prod means mostly that some internal endpoints are not exposed
    env: prod
    external_env_domain: social.network
  # For demo mode only, we don't need to keep websocket connections open on upgrade:
  drainTimeout: 10
  terminationGracePeriodSeconds: 30

webapp:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  config:
    externalUrls:
      backendRest: nginz-https-dev.social.network
      backendWebsocket: nginz-ssl-dev.social.network
      backendDomain: social.network
      appHost: webapp-dev.social.network
  
  envVars: {
    CSP_EXTRA_CONNECT_SRC: "https://*.social.network, wss://*.social.network",
    CSP_EXTRA_IMG_SRC: "https://*.social.network",
    CSP_EXTRA_SCRIPT_SRC: "https://*.social.network",
    CSP_EXTRA_DEFAULT_SRC: "https://*.social.network",
    CSP_EXTRA_FONT_SRC: "https://*.social.network",
    CSP_EXTRA_FRAME_SRC: "https://*.social.network",
    CSP_EXTRA_MANIFEST_SRC: "https://*.social.network",
    CSP_EXTRA_OBJECT_SRC: "https://*.social.network",
    CSP_EXTRA_MEDIA_SRC: "https://*.social.network",
    CSP_EXTRA_PREFETCH_SRC: "https://*.social.network",
    CSP_EXTRA_STYLE_SRC: "https://*.social.network",
    CSP_EXTRA_WORKER_SRC: "https://*.social.network"
  }

team-settings:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  config:
    externalUrls:
      backendRest: nginz-https-dev.social.network
      backendWebsocket: nginz-ssl-dev.social.network
      backendDomain: social.network
      appHost: webapp-dev.social.network

  envVars: {
    CSP_EXTRA_CONNECT_SRC: "https://*.social.network, wss://*.social.network",
    CSP_EXTRA_IMG_SRC: "https://*.social.network",
    CSP_EXTRA_SCRIPT_SRC: "https://*.social.network",
    CSP_EXTRA_DEFAULT_SRC: "https://*.social.network",
    CSP_EXTRA_FONT_SRC: "https://*.social.network",
    CSP_EXTRA_FRAME_SRC: "https://*.social.network",
    CSP_EXTRA_MANIFEST_SRC: "https://*.social.network",
    CSP_EXTRA_OBJECT_SRC: "https://*.social.network",
    CSP_EXTRA_MEDIA_SRC: "https://*.social.network",
    CSP_EXTRA_PREFETCH_SRC: "https://*.social.network",
    CSP_EXTRA_STYLE_SRC: "https://*.social.network",
    CSP_EXTRA_WORKER_SRC: "https://*.social.network"
  }

account-pages:
  replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
  config:
    externalUrls:
      backendRest: nginz-https-dev.social.network
      backendDomain: social.network
      appHost: app-dev.social.network

  envVars: {
    CSP_EXTRA_CONNECT_SRC: "https://*.social.network, wss://*.social.network",
    CSP_EXTRA_IMG_SRC: "https://*.social.network",
    CSP_EXTRA_SCRIPT_SRC: "https://*.social.network",
    CSP_EXTRA_DEFAULT_SRC: "https://*.social.network",
    CSP_EXTRA_FONT_SRC: "https://*.social.network",
    CSP_EXTRA_FRAME_SRC: "https://*.social.network",
    CSP_EXTRA_MANIFEST_SRC: "https://*.social.network",
    CSP_EXTRA_OBJECT_SRC: "https://*.social.network",
    CSP_EXTRA_MEDIA_SRC: "https://*.social.network",
    CSP_EXTRA_PREFETCH_SRC: "https://*.social.network",
    CSP_EXTRA_STYLE_SRC: "https://*.social.network",
    CSP_EXTRA_WORKER_SRC: "https://*.social.network"
  }
